"""SQLAlchemy models for epaData.

Written in SQLAlchemy 2.0 typed declarative style: columns are declared with
``Mapped[...]`` annotations, and ``Mapped[Optional[...]]`` marks a column
nullable without repeating ``nullable=True``.

Schema overview::

    Dataset  1---* AnnualRecord *---1  Unit  *---1  Facility
"""

from datetime import date, datetime, timezone
from typing import Optional

from sqlalchemy import Date, DateTime, ForeignKey, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app import db


def utcnow() -> datetime:
    """Timezone-aware UTC timestamp used as a column default."""
    return datetime.now(timezone.utc)


class Dataset(db.Model):
    """One ingestion run: a single file or API pull from an EPA source."""

    __tablename__ = "datasets"

    id: Mapped[int] = mapped_column(primary_key=True)
    dataset_name: Mapped[str] = mapped_column(String(150))
    data_source: Mapped[str] = mapped_column(String(150))
    reporting_year: Mapped[int]
    retrieval_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow
    )
    original_filename: Mapped[Optional[str]] = mapped_column(String(255))
    raw_records: Mapped[int] = mapped_column(default=0)
    accepted_records: Mapped[int] = mapped_column(default=0)
    notes: Mapped[Optional[str]] = mapped_column(Text)

    annual_records: Mapped[list["AnnualRecord"]] = relationship(
        back_populates="dataset",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Dataset {self.id} {self.dataset_name!r} ({self.reporting_year})>"


class Facility(db.Model):
    """A power plant / emissions facility, keyed by its EPA-assigned ID."""

    __tablename__ = "facilities"

    # EPA assigns this ID, so it is never auto-generated by the database.
    epa_facility_id: Mapped[int] = mapped_column(primary_key=True, autoincrement=False)
    facility_name: Mapped[str] = mapped_column(String(255))
    state_code: Mapped[str] = mapped_column(String(2))
    county: Mapped[str] = mapped_column(String(100))
    latitude: Mapped[float]
    longitude: Mapped[float]
    source_category: Mapped[str] = mapped_column(String(150))

    units: Mapped[list["Unit"]] = relationship(
        back_populates="facility",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Facility {self.epa_facility_id} {self.facility_name!r}>"


class Unit(db.Model):
    """A single combustion / generating unit belonging to a facility.

    ``epa_unit_id`` is only unique within a facility, so an internal surrogate
    key is used as the primary key.
    """

    __tablename__ = "units"

    internal_unit_key: Mapped[int] = mapped_column(primary_key=True)
    facility_id: Mapped[int] = mapped_column(
        ForeignKey("facilities.epa_facility_id", ondelete="CASCADE"),
        index=True,
    )
    epa_unit_id: Mapped[str] = mapped_column(String(50))
    unit_type: Mapped[str] = mapped_column(String(100))
    primary_fuel: Mapped[str] = mapped_column(String(100))
    secondary_fuel: Mapped[Optional[str]] = mapped_column(String(100))
    operating_date: Mapped[Optional[date]] = mapped_column(Date)
    retirement_date: Mapped[Optional[date]] = mapped_column(Date)

    facility: Mapped["Facility"] = relationship(back_populates="units")
    annual_records: Mapped[list["AnnualRecord"]] = relationship(
        back_populates="unit",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Unit {self.internal_unit_key} facility={self.facility_id} {self.epa_unit_id!r}>"


class AnnualRecord(db.Model):
    """Annual emissions and operating totals reported for one unit."""

    __tablename__ = "annual_records"
    __table_args__ = (
        UniqueConstraint("unit_id", "reporting_year", name="uq_unit_reporting_year"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    unit_id: Mapped[int] = mapped_column(
        ForeignKey("units.internal_unit_key", ondelete="CASCADE"),
        index=True,
    )
    dataset_id: Mapped[int] = mapped_column(
        ForeignKey("datasets.id", ondelete="CASCADE"),
        index=True,
    )
    reporting_year: Mapped[int] = mapped_column(index=True)

    operating_time: Mapped[float]
    gross_load: Mapped[float]
    steam_load: Mapped[Optional[float]]
    heat_input: Mapped[float]

    co2_mass: Mapped[float]
    so2_mass: Mapped[float]
    nox_mass: Mapped[float]

    so2_control: Mapped[Optional[str]] = mapped_column(String(150))
    nox_control: Mapped[Optional[str]] = mapped_column(String(150))
    pm_control: Mapped[Optional[str]] = mapped_column(String(150))
    program_code: Mapped[Optional[str]] = mapped_column(String(100))

    unit: Mapped["Unit"] = relationship(back_populates="annual_records")
    dataset: Mapped["Dataset"] = relationship(back_populates="annual_records")

    def __repr__(self) -> str:
        return f"<AnnualRecord unit={self.unit_id} year={self.reporting_year}>"
