"""initial schema

Revision ID: 4eb2099c9e73
Revises: 
Create Date: 2026-09-02 00:48:17.813866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb2099c9e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=150), nullable=False),
    sa.Column('data_source', sa.String(length=150), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('retrieval_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_records', sa.Integer(), nullable=False),
    sa.Column('accepted_records', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('epa_facility_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source_category', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('epa_facility_id')
    )
    op.create_table('units',
    sa.Column('internal_unit_key', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('epa_unit_id', sa.String(length=50), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=False),
    sa.Column('primary_fuel', sa.String(length=100), nullable=False),
    sa.Column('secondary_fuel', sa.String(length=100), nullable=True),
    sa.Column('operating_date', sa.Date(), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.epa_facility_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('internal_unit_key')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_facility_id'), ['facility_id'], unique=False)

    op.create_table('annual_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('operating_time', sa.Float(), nullable=False),
    sa.Column('gross_load', sa.Float(), nullable=False),
    sa.Column('steam_load', sa.Float(), nullable=True),
    sa.Column('heat_input', sa.Float(), nullable=False),
    sa.Column('co2_mass', sa.Float(), nullable=False),
    sa.Column('so2_mass', sa.Float(), nullable=False),
    sa.Column('nox_mass', sa.Float(), nullable=False),
    sa.Column('so2_control', sa.String(length=150), nullable=True),
    sa.Column('nox_control', sa.String(length=150), nullable=True),
    sa.Column('pm_control', sa.String(length=150), nullable=True),
    sa.Column('program_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.internal_unit_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'reporting_year', name='uq_unit_reporting_year')
    )
    with op.batch_alter_table('annual_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annual_records_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annual_records_reporting_year'), ['reporting_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_annual_records_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annual_records_unit_id'))
        batch_op.drop_index(batch_op.f('ix_annual_records_reporting_year'))
        batch_op.drop_index(batch_op.f('ix_annual_records_dataset_id'))

    op.drop_table('annual_records')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_facility_id'))

    op.drop_table('units')
    op.drop_table('facilities')
    op.drop_table('datasets')
    # ### end Alembic commands ###
